### PR TITLE
ADPCM, Crypto and hash table revision.

### PR DESCRIPTION
**Pull request by DrSuperGood**
Minor revision to ADPCM code for maintainability. Fixed a possible type cast logic error. Mostly documentation for maintainability.

Rewrote the MPQ cryptographic code to be more maintainable. Broke hashing and encryption into separate classes. Removed a lot of magic numbers from the code. Added support for processing buffers containing partial data.

Also revised the hash table code. Added locale support (not exposed at top level API yet). Correctly process deleted buckets when looking for files. Added more methods to modify hash table for future use.

Block table has not been revised outside of the cryptographic calls. Revision of this will occur at a later time as it is heavily coupled with file IO at the moment so might require a large revision. In the mean time it is probably a good idea to merge in these changes.

### CODE REVIEW

**Comment by DrSuperGood** [comment]
Judging by the coverage drop, it is possible this commit has broken something in such a way that the automated tests are not picking it up as a failure.

**Comment by Frotty** [comment]
seems like it. Now testIncompressibleFile is failing. You can also run the tests on your pc btw.

Thanks for the nice additions, hope to merge soon :) !

**Comment by DrSuperGood** [comment]
These coverage checks are strict!

I will write a test method for the hash table which will cover the currently unused functionality.

**Comment by Frotty** [comment]
I don't think losing 1% is crucial, but yeah, it would be nice if you could add mpq examples that cover those cases (deleted bucket and different locale i believe?)

**Comment by DrSuperGood** [comment]
I give up trying to raise the coverage any more than that.

**Comment by Frotty** [comment]
This is ready to merge then I assume?

**Comment by DrSuperGood** [comment]
> This is ready to merge then I assume?

As read as it ever will be. I am not getting that extra 0.1% coverage.

**Comment by Frotty** [comment]
Alright, thanks a lot again 👍 

The changes are included in release 1.5.0

**Pull request merged**
