### PR TITLE
Proposal to use the new JPMS model and use Travis-ci to build & test against Java 9 & 11

### PR DESCRIPTION
**Pull request by Warkdev**
Hi,

This is in reaction to the following issue: https://github.com/inwc3/JMPQ3/issues/27

### CODE REVIEW

**Comment by Frotty** [comment]
Hey, thanks for the PR 🍰 
Looks good so far apart from the whitespace changes.
Please revert those ones in `MpqTests.java`. Then i can merge this.

**Comment by Warkdev** [comment]
Here you are, sorry for that, my IDE is introducing those, I must check why.

**Comment by Frotty** [comment]
check here: https://github.com/inwc3/JMPQ3/pull/28/files#diff-59152c8afada68aad461481629115b78

Since there are only few changes, might be easier to revert completely.
We should probably add .editorconfig

**Comment by Warkdev** [comment]
Updated as well.

**Comment by Warkdev** [comment]
It obviously fails on oracle 8 and 9... Since I compiled on 11. I may lower this to jdk 9 but as the JPMS didn't exist in jdk8, it's a breaking point. Which trade-off would you prefer? I'll keep working with the modularized version anyway and will keep syncing your commits on my repo.

**Comment by Frotty** [comment]
Probably just keep on a branch and merge when we move all projects to 11+

**Comment by Warkdev** [comment]
Good idea, I'll do that and do a proper commit + PR request again.

**Comment by Frotty** [comment]
Alright, I created a java9-module branch https://github.com/inwc3/JMPQ3/tree/java9-module
You should open a new PR for that branch and I will merge. 
You can then get the artifact from https://jitpack.io/#inwc3/jmpq3 by selecting the new branch from the dropdown

**Pull request closed without merging**
